architectury brainrot Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/player/LocalPlayer
	at TRANSFORMER/architectury@17.0.6/dev.architectury.networking.NetworkManager.getAdaptor(NetworkManager.java) ~[architectury-neoforge-17.0.6.jar%23225!/:?] {re:classloading}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at TRANSFORMER/architectury@17.0.6/dev.architectury.impl.NetworkAggregator.lambda$static$0(NetworkAggregator.java:51) ~[architectury-neoforge-17.0.6.jar%23225!/:?] {re:classloading}
	... 20 more
Caused by: java.lang.ClassNotFoundException: Attempted to load class net.minecraft.client.player.LocalPlayer which is not present on the dedicated server